---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: https://api.stackbit.com/project/5e85d8b89673b90014b78fff/webhook/forestry
sections:
- type: document
  path: Startseite.yml
  label: Startseite
  templates:
  - config
- type: document
  path: _data/fastreceipes.yml
  label: schnelle Rezepte
  templates:
  - header
- type: document
  path: _data/receipeswithmeet.yml
  label: Rezepte mit Fleisch
  templates:
  - contact
- type: document
  path: _data/vegetarianreceipesl.yml
  label: Vegetarische Rezepte
  templates:
  - social
- type: document
  path: _data/verganreceipes.yml
  label: Vegane Rezepte
  templates:
  - footer
upload_dir: images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
